- name: Add repository mariadb
  template:
   src: influxdata.repo.j2
   dest: /etc/yum.repos.d/influxdata.repo.j2

- name: install TICK
  yum:
   name: "{{item}}"
   state: latest
   state: started
   enabled: yes
  with_items:
   - influxdb
   - telegraf
   - kapacitor
   - chronograf
